### ISSUE TITLE
执行时遇到找不到mysql的问题

### ISSUE THREAD

**Issue by kawamao** [chenzhe07/Atlas_auto_setline#1]
你好，我在执行时出现下面的错误，不过我的PATH里已经有mysql存在了，请问这是什么样的问题呢？
which: no mysql in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/java/bin:/usr/local/mysql/bin/mysql:/root/bin)
Unable to fine mysql command in your $PATH.

**Comment by arstercz** [comment]
你是 export PATH 设置的吗?  这样脚本执行是其新的进程, export 不会在脚本生效. 可以写到 .bash_profile 里, source .bash_profile 使它生效.

**Comment by kawamao** [comment]
写在.bash_profile里可以执行了，不过执行的时候又出现新的错误信息
[root@S-C6 Atlas_auto_setline-master]# perl atlas_auto_setline.pl --conf=db.conf --verbose --setline --threshold=30
Warning: Using a password on the command line interface can be insecure.
ERROR 2005 (HY000): Unknown MySQL server host '172.16.1.14,172.16.1.15' (74)
 +-- error in get slave 172.16.1.14,172.16.1.15:3306 info.
db.conf里的slave host配置是这样的
slave_host:172.16.1.14,172.16.1.15

**Comment by kawamao** [comment]
完整的错误信息是这样的
Warning: Using a password on the command line interface can be insecure.
ERROR 2005 (HY000): Unknown MySQL server host '172.16.1.14,172.16.1.15' (74)
 +-- error in get slave 172.16.1.14,172.16.1.15:3306 info.
Warning: Using a password on the command line interface can be insecure.
Use of uninitialized value in addition (+) at atlas_auto_setline.pl line 237.

**Comment by kawamao** [comment]
我知道了。。。【,】跟ip后面空白的问题^^"

**Comment by kawamao** [comment]
感谢：）
